ci: add publish via OIDC

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -7,6 +7,8 @@ default:
     key: ${CI_COMMIT_REF_SLUG}-${RUST_VERSION}
     paths:
       - target/
+  rules:
+    - if: $CI_COMMIT_BRANCH
   script:
     - cargo build --verbose
     - cargo test --verbose
@@ -24,6 +26,8 @@ fmt:
   stage: test
   image: docker.io/rustlang/rust:nightly
   needs: []
+  rules:
+    - if: $CI_COMMIT_BRANCH
   before_script:
     - rustup component add rustfmt
   script:
@@ -33,7 +37,43 @@ clippy:
   stage: test
   needs: []
   image: rust:latest
+  rules:
+    - if: $CI_COMMIT_BRANCH
   before_script:
     - rustup component add clippy
   script:
     - cargo clippy
+
+publish:
+  image: rust:alpine
+  stage: deploy
+  environment: release
+  rules:
+    - if: $CI_COMMIT_TAG
+  id_tokens:
+    CRATES_IO_ID_TOKEN:
+      aud: crates.io
+  before_script:
+    - apk add --no-cache bash curl jq
+  script:
+    - |
+      set -e
+
+      # Exchange JWT token
+      echo "Exchanging OIDC token..." >&2
+      RESPONSE=$(curl -s -X POST https://crates.io/api/v1/trusted_publishing/tokens \
+        -H "Content-Type: application/json" \
+        -d "{\"jwt\": \"$CRATES_IO_ID_TOKEN\"}")
+
+      # Extract publish token
+      CRATES_IO_PUBLISH_TOKEN=$(echo "$RESPONSE" | jq -r '.token')
+
+      if [ "$CRATES_IO_PUBLISH_TOKEN" = "null" ] || [ -z "$CRATES_IO_PUBLISH_TOKEN" ]; then
+        echo "Failed to get upload token" >&2
+        echo "$RESPONSE" >&2
+        exit 1
+      fi
+
+      echo "$CRATES_IO_PUBLISH_TOKEN"
+
+      CARGO_REGISTRY_TOKEN="$CRATES_IO_PUBLISH_TOKEN" cargo publish
